stages:
  preprocess_dataset_1:
    cmd: PREPROCESS_CONFIG=config/dvc/dataset_1.yaml python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - config/dvc/dataset_1.yaml
      - data/raw/train.csv
    outs:
      - data/processed/train_dataset_1.csv:
          cache: false
          persist: true
  preprocess_dataset_2:
    cmd: PREPROCESS_CONFIG=config/dvc/dataset_2.yaml python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - config/dvc/dataset_2.yaml
      - data/raw/train.csv
    outs:
      - data/processed/train_dataset_2.csv:
          cache: false
          persist: true
  preprocess_dataset_3:
    cmd: PREPROCESS_CONFIG=config/dvc/dataset_3.yaml python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - config/dvc/dataset_3.yaml
      - data/raw/train.csv
    outs:
      - data/processed/train_dataset_3.csv:
          cache: false
          persist: true
  preprocess_dataset_4:
    cmd: PREPROCESS_CONFIG=config/dvc/dataset_4.yaml python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - config/dvc/dataset_4.yaml
      - data/raw/train.csv
    outs:
      - data/processed/train_dataset_4.csv:
          cache: false
          persist: true
  