stages:
  build-base:
    cmd: BASE_CONFIG=config/dvc/base.yaml python src/data/download.py
    deps:
      - src/data/download.py
      - config/dvc/base.yaml
    outs:
      - data/raw/base.parquet

  preprocess:
    cmd: PREPROCESS_CONFIG=config/dvc/base.yaml python src/data/preprocess.py
    deps:
      - src/data/preprocess.py
      - config/dvc/preprocess.yaml
      - data/raw/base.parquet
    outs:
      - data/interim/base.parquet
      - data/interim/topics.parquet

  process_dataset_1:
    cmd: PROCESS_CONFIG=config/dvc/dataset_1.yaml python src/data/process.py
    deps:
      - src/data/process.py
      - config/dvc/dataset_1.yaml
      - data/interim/base.parquet
      - data/interim/topics.parquet
    outs:
      - data/processed/train_dataset_1.csv:
          cache: false
          persist: true
      - data/processed/test_dataset_1.csv:
          cache: false
          persist: true

  process_dataset_2:
    cmd: PROCESS_CONFIG=config/dvc/dataset_2.yaml python src/data/process.py
    deps:
      - src/data/process.py
      - config/dvc/dataset_2.yaml
      - data/interim/base.parquet
      - data/interim/topics.parquet
    outs:
      - data/processed/train_dataset_2.csv:
          cache: false
          persist: true
      - data/processed/test_dataset_2.csv:
         cache: false
         persist: true
  
  