interim_path: "data/interim"
dataset_name: "clmentbisaillon/fake-and-real-news-dataset"
entity_model_name: "dbmdz/bert-large-cased-finetuned-conll03-english"
label_name: "is_bs"
feature_name: "text"

