interim_path: "data/interim"
entity_model_name: "dbmdz/bert-large-cased-finetuned-conll03-english"
file_name: "base.parquet"
embedding_model_name: "all-MiniLM-L6-v2"
n_neighbors: 30
n_components: 5
min_dist: 0.4
metric: 'euclidean'
min_cluster_size: 60
cluster_selection_method: 'eom'